import Head from 'next/head'
import Image from 'next/image'

import styled from 'styled-components'
import Button1 from '../components/Button1';
import Button2 from '../components/Button2';
import Button3 from '../components/Button3';
import Counter from '../components/Counter';
import RadioInput from '../components/RadioInput';
import TextInput from '../components/TextInput';


export default function Home() {
  
  return (
    <div >
      <Head>
        <title>Audiophile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Button1>see product</Button1>
      <Button2>see product</Button2>
      <Button3/>
      <TextInput/>
      <RadioInput/>
      <Counter/>
      
    </div>
  )
}

 const Container = styled.div`
  background: ${props => props.theme.accent};
  width: 100%;
  height: 100px;
`;
